@extends('pcap.layout')
@section('title')
    PCAP Connections
@endsection
@section('content')
    <section class="main_content dashboard_part">
        <div class="main_content_iner ">
            <div class="container-fluid plr_30 body_white_bg pt_30">
                <ul class="breadcrumbs-one">
                    <li>
                        <a href=""><i class="fas fa-list-ul text-black"></i></a>
                    </li>
                    <li>
                        <a href="" class="ml-15 text-black">filename.pcap</a>
                    </li>
                    <li>
                        <a href="" class="ml-15 text-black"><b>Connections</b></a>
                    </li>
                    <li>
                        <a href="" class="ml-15 text-black btn-padding ml-350">Copy Url</a>
                    </li>
                    <li>
                        <a href="" class="ml-15 text-black btn-padding">Download File</a>
                    </li>
                </ul>
                <div class="QA_table ">

                    <table class="table lms_table_active">
                        <thead>
                            <tr>
                                <th scope="col">IP</th>
                                <th scope="col">DNS</th>
                                <th scope="col">Bytes</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>
                            <tr>
                                <td>192.168.1.111</td>
                                <td>10.10.10.138:161</td>
                                <td>10Bytes</td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </section>
@endsection
